// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0bd7da20-7359-4f99-b1ac-32380a347440",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SOPmT0WkV",
    "aws_user_pools_web_client_id": "5jlij65agq1ai5h8qv6084k395",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://iexxeriymzejvpgbzt2qfngsm4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://7sm5a5fsjk.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "covid-tracee4f729503145413ab1bc281c2654953ddev-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
